export const modules = [
  {
    id: "portal",
    label: "Portal",
    short: "PO",
    summary: "Unified entry and module routing",
    status: "Ready",
  },
  {
    id: "cost",
    label: "Cost Overview",
    short: "CO",
    summary: "Budget, actuals, variance and actions",
    status: "Ready",
  },
  {
    id: "materials",
    label: "Material Library",
    short: "ML",
    summary: "Price library and AI import review",
    status: "Ready",
  },
  {
    id: "costMap",
    label: "Cost Map",
    short: "CM",
    summary: "Regional standards and benchmark pricing",
    status: "Ready",
  },
  {
    id: "contracts",
    label: "Contracts",
    short: "CT",
    summary: "Payment progress and risk exposure",
    status: "Ready",
  },
  {
    id: "smartQA",
    label: "Smart Q&A",
    short: "QA",
    summary: "Local matching, OCR mock and AI answer flow",
    status: "Ready",
  },
  {
    id: "accounts",
    label: "Accounts",
    short: "AC",
    summary: "Roles, access and approval boundaries",
    status: "Ready",
  },
];

export const portfolio = {
  regions: [
    "All Regions",
    "Region A",
    "Region B",
    "Region C",
    "Region D",
    "Region E",
    "Region F",
    "Region G",
  ],
  projects: [
    "All Projects",
    "Project Alpha",
    "Project Beta",
    "Project Gamma",
    "Project Delta",
    "Project Echo",
    "Project Foxtrot",
    "Project Harbor",
    "Project Iota",
  ],
  asOf: "Demo snapshot: 2026-Q2",
};

export const portalStats = [
  { label: "Managed Projects", value: "86", trend: "12 demo regions" },
  { label: "Annual Cost Scope", value: "$248.6M", trend: "Synthetic portfolio" },
  { label: "Material Prices", value: "18,420", trend: "Mock library rows" },
  { label: "Contract Exposure", value: "$96.8M", trend: "312 demo contracts" },
  { label: "AI Review Tasks", value: "1,284", trend: "Static simulations" },
  { label: "Permission Events", value: "4,906", trend: "Role audit mock" },
];

export const costKpis = [
  { label: "Annual Budget", value: "$248.6M", delta: "86 projects", tone: "neutral" },
  { label: "Actual Cost", value: "$118.4M", delta: "47.6% used", tone: "good" },
  { label: "Forecast", value: "$257.9M", delta: "+3.7% vs budget", tone: "warning" },
  { label: "Open Actions", value: "186", delta: "42 high priority", tone: "danger" },
  { label: "AI Matched Issues", value: "3,842", delta: "mock knowledge hits", tone: "neutral" },
  { label: "Savings Pipeline", value: "$8.74M", delta: "review in progress", tone: "good" },
];

export const costTrend = [
  { month: "Jan", budget: 18.2, actual: 17.4, paid: 13.2 },
  { month: "Feb", budget: 18.6, actual: 18.1, paid: 13.8 },
  { month: "Mar", budget: 19.4, actual: 20.6, paid: 15.4 },
  { month: "Apr", budget: 20.1, actual: 21.7, paid: 16.3 },
  { month: "May", budget: 20.8, actual: 22.2, paid: 17.1 },
  { month: "Jun", budget: 21.1, actual: 22.8, paid: 17.6 },
  { month: "Jul", budget: 21.7, actual: 22.4, paid: 18.2 },
  { month: "Aug", budget: 21.4, actual: 21.1, paid: 18.6 },
  { month: "Sep", budget: 20.6, actual: 20.9, paid: 18.8 },
  { month: "Oct", budget: 21.9, actual: 22.6, paid: 19.4 },
  { month: "Nov", budget: 21.6, actual: 21.8, paid: 19.9 },
  { month: "Dec", budget: 23.2, actual: 23.7, paid: 20.4 },
];

export const costRows = [
  {
    area: "Region A",
    project: "Project Alpha",
    subject: "Security Service",
    budget: "$1.82M",
    actual: "$1.96M",
    variance: "+7.7%",
    owner: "Cost Ops",
    tone: "danger",
  },
  {
    area: "Region A",
    project: "Project Beta",
    subject: "Cleaning Service",
    budget: "$1.24M",
    actual: "$1.18M",
    variance: "-4.8%",
    owner: "Site Ops",
    tone: "good",
  },
  {
    area: "Region B",
    project: "Project Gamma",
    subject: "Maintenance",
    budget: "$0.96M",
    actual: "$1.02M",
    variance: "+6.3%",
    owner: "Engineering",
    tone: "warning",
  },
  {
    area: "Region C",
    project: "Project Delta",
    subject: "Utilities",
    budget: "$2.10M",
    actual: "$2.06M",
    variance: "-1.9%",
    owner: "Energy Desk",
    tone: "good",
  },
  {
    area: "Region D",
    project: "Project Echo",
    subject: "Elevator Maintenance",
    budget: "$1.36M",
    actual: "$1.48M",
    variance: "+8.8%",
    owner: "Asset Desk",
    tone: "danger",
  },
  {
    area: "Region E",
    project: "Project Foxtrot",
    subject: "Landscape",
    budget: "$0.74M",
    actual: "$0.69M",
    variance: "-6.8%",
    owner: "Site Ops",
    tone: "good",
  },
  {
    area: "Region F",
    project: "Project Harbor",
    subject: "Public Area Repair",
    budget: "$0.58M",
    actual: "$0.66M",
    variance: "+13.8%",
    owner: "Engineering",
    tone: "danger",
  },
  {
    area: "Region G",
    project: "Project Iota",
    subject: "Consumables",
    budget: "$0.42M",
    actual: "$0.40M",
    variance: "-4.8%",
    owner: "Procurement",
    tone: "good",
  },
  {
    area: "Region H",
    project: "Project Jade",
    subject: "Fire System Testing",
    budget: "$0.88M",
    actual: "$0.97M",
    variance: "+10.2%",
    owner: "Asset Desk",
    tone: "danger",
  },
  {
    area: "Region I",
    project: "Project Kappa",
    subject: "Parking Operation",
    budget: "$0.62M",
    actual: "$0.55M",
    variance: "-11.3%",
    owner: "Commercial Ops",
    tone: "good",
  },
  {
    area: "Region J",
    project: "Project Lumen",
    subject: "Energy Inspection",
    budget: "$0.71M",
    actual: "$0.79M",
    variance: "+11.3%",
    owner: "Energy Desk",
    tone: "warning",
  },
  {
    area: "Region K",
    project: "Project Metro",
    subject: "Pest Control",
    budget: "$0.28M",
    actual: "$0.26M",
    variance: "-7.1%",
    owner: "Site Ops",
    tone: "good",
  },
];

export const commandCenter = [
  { label: "Cost variance under review", value: "$9.26M", meta: "Across 41 projects", tone: "danger" },
  { label: "Contract payment lag", value: "$4.18M", meta: "26 demo items", tone: "warning" },
  { label: "Material price opportunities", value: "$2.34M", meta: "143 benchmark gaps", tone: "good" },
  { label: "Permission anomalies blocked", value: "37", meta: "No privileged bypass", tone: "neutral" },
];

export const moduleHealth = [
  { module: "Cost Overview", coverage: "86 projects", signal: "42 high-priority actions", health: "Watch" },
  { module: "Material Library", coverage: "18,420 prices", signal: "143 benchmark opportunities", health: "Good" },
  { module: "Cost Map", coverage: "12 regions", signal: "31 standards above band", health: "Watch" },
  { module: "Contracts", coverage: "312 contracts", signal: "26 payment lag cases", health: "Watch" },
  { module: "Smart Q&A", coverage: "3,842 matches", signal: "1,284 AI tasks simulated", health: "Good" },
  { module: "Permissions", coverage: "4 roles", signal: "37 blocked demo events", health: "Good" },
];

export const operationsFeed = [
  { time: "09:05", event: "AI import recognized 42 candidate material rows", owner: "Material Desk" },
  { time: "09:18", event: "Cost map found 9 security benchmarks above demo band", owner: "Cost Ops" },
  { time: "09:42", event: "Contract risk queue grouped 6 high-risk payment lags", owner: "Contract Desk" },
  { time: "10:06", event: "Smart Q&A matched policy case CT-02 for payment review", owner: "AI Assistant" },
  { time: "10:31", event: "Permission center blocked external full-library access", owner: "Access Control" },
];

export const materials = [
  {
    name: "Demo Concrete C30",
    category: "Construction",
    unit: "m3",
    city: "Region A",
    supplier: "Supplier Alpha",
    current: "$102.40",
    tax: "6%",
    change: "+2.4%",
    status: "Confirmed",
  },
  {
    name: "Demo LED Panel",
    category: "Electrical",
    unit: "set",
    city: "Region B",
    supplier: "Supplier Beta",
    current: "$18.60",
    tax: "13%",
    change: "-1.1%",
    status: "Confirmed",
  },
  {
    name: "Demo Cleaning Agent",
    category: "Consumables",
    unit: "bottle",
    city: "Region A",
    supplier: "Supplier Gamma",
    current: "$4.85",
    tax: "6%",
    change: "+0.6%",
    status: "Review",
  },
  {
    name: "Demo Elevator Part",
    category: "Maintenance",
    unit: "piece",
    city: "Region C",
    supplier: "Supplier Delta",
    current: "$76.20",
    tax: "13%",
    change: "+3.2%",
    status: "Confirmed",
  },
  {
    name: "Demo Planting Soil",
    category: "Landscape",
    unit: "ton",
    city: "Region B",
    supplier: "Supplier Echo",
    current: "$36.50",
    tax: "9%",
    change: "-2.8%",
    status: "Review",
  },
  {
    name: "Demo Fire Pump Seal",
    category: "Maintenance",
    unit: "set",
    city: "Region D",
    supplier: "Supplier Fox",
    current: "$42.90",
    tax: "13%",
    change: "+4.1%",
    status: "Review",
  },
  {
    name: "Demo Access Card",
    category: "Operations",
    unit: "piece",
    city: "Region A",
    supplier: "Supplier Grid",
    current: "$1.15",
    tax: "13%",
    change: "-0.8%",
    status: "Confirmed",
  },
  {
    name: "Demo Waterproof Coating",
    category: "Repair",
    unit: "kg",
    city: "Region F",
    supplier: "Supplier Halo",
    current: "$6.70",
    tax: "9%",
    change: "+6.5%",
    status: "Review",
  },
  {
    name: "Demo Gate Motor",
    category: "Operations",
    unit: "set",
    city: "Region G",
    supplier: "Supplier Ion",
    current: "$128.30",
    tax: "13%",
    change: "+1.9%",
    status: "Confirmed",
  },
  {
    name: "Demo Meter Cabinet",
    category: "Electrical",
    unit: "unit",
    city: "Region H",
    supplier: "Supplier Juno",
    current: "$218.00",
    tax: "13%",
    change: "-3.4%",
    status: "Confirmed",
  },
  {
    name: "Demo Patrol Device",
    category: "Security",
    unit: "piece",
    city: "Region D",
    supplier: "Supplier Kite",
    current: "$54.80",
    tax: "13%",
    change: "+2.8%",
    status: "Review",
  },
  {
    name: "Demo Filter Cartridge",
    category: "Maintenance",
    unit: "piece",
    city: "Region F",
    supplier: "Supplier Loom",
    current: "$9.60",
    tax: "6%",
    change: "-1.6%",
    status: "Confirmed",
  },
];

export const materialCandidates = [
  {
    source: "mock-price-list-alpha.xlsx",
    extracted: "Demo Pipe DN50",
    confidence: "92%",
    action: "Needs unit check",
  },
  {
    source: "mock-bid-sheet-beta.xlsx",
    extracted: "Demo Sensor Kit",
    confidence: "88%",
    action: "Ready to confirm",
  },
  {
    source: "mock-maintenance-quote.xlsx",
    extracted: "Demo Valve Assembly",
    confidence: "81%",
    action: "Supplier review",
  },
  {
    source: "mock-security-bundle.xlsx",
    extracted: "Demo Patrol Device",
    confidence: "94%",
    action: "Ready to confirm",
  },
  {
    source: "mock-energy-ledger.xlsx",
    extracted: "Demo Meter Cabinet",
    confidence: "86%",
    action: "Tax rate check",
  },
  {
    source: "mock-repair-batch.xlsx",
    extracted: "Demo Waterproof Coating",
    confidence: "79%",
    action: "Category review",
  },
];

export const costMapRegions = [
  {
    region: "Region A",
    benchmark: "$4.12 / m2",
    variance: "+3.1%",
    grade: "B",
    drivers: ["Security staffing", "Cleaning frequency", "Lift count"],
  },
  {
    region: "Region B",
    benchmark: "$3.74 / m2",
    variance: "-2.6%",
    grade: "A",
    drivers: ["Energy savings", "Shared vendor pool", "Compact layout"],
  },
  {
    region: "Region C",
    benchmark: "$4.48 / m2",
    variance: "+7.8%",
    grade: "C",
    drivers: ["Aging assets", "Emergency repair", "Seasonal landscaping"],
  },
  {
    region: "Region D",
    benchmark: "$4.01 / m2",
    variance: "+1.6%",
    grade: "B",
    drivers: ["Lift maintenance", "Fire system", "Weekend staffing"],
  },
  {
    region: "Region E",
    benchmark: "$3.42 / m2",
    variance: "-5.4%",
    grade: "A",
    drivers: ["Vendor pooling", "Energy controls", "Low repair rate"],
  },
  {
    region: "Region F",
    benchmark: "$4.72 / m2",
    variance: "+11.2%",
    grade: "C",
    drivers: ["Waterproof repair", "Aging pumps", "Small contract base"],
  },
  {
    region: "Region G",
    benchmark: "$3.91 / m2",
    variance: "+0.8%",
    grade: "B",
    drivers: ["Parking operation", "Gate systems", "Night patrol"],
  },
  {
    region: "Region H",
    benchmark: "$4.35 / m2",
    variance: "+6.2%",
    grade: "C",
    drivers: ["Fire testing", "High-rise assets", "Repair backlog"],
  },
];

export const costMapItems = [
  { item: "Security Post", standard: "$3,900 / person-month", current: "$4,020", state: "Watch" },
  { item: "Cleaning Labor", standard: "$3,200 / person-month", current: "$3,080", state: "Normal" },
  { item: "Green Care", standard: "$0.95 / m2-month", current: "$1.04", state: "Watch" },
  { item: "Elevator Maint.", standard: "$820 / unit-month", current: "$812", state: "Normal" },
  { item: "Fire Pump Maint.", standard: "$1,180 / set-month", current: "$1,320", state: "Watch" },
  { item: "Public Repair", standard: "$0.42 / m2-month", current: "$0.51", state: "Watch" },
  { item: "Consumables", standard: "$0.18 / m2-month", current: "$0.16", state: "Normal" },
  { item: "Energy Inspection", standard: "$680 / site-month", current: "$642", state: "Normal" },
];

export const costMapMatrix = [
  { region: "Region A", security: 84, cleaning: 71, landscape: 66, elevator: 79, repair: 88 },
  { region: "Region B", security: 58, cleaning: 62, landscape: 49, elevator: 61, repair: 55 },
  { region: "Region C", security: 91, cleaning: 77, landscape: 86, elevator: 82, repair: 94 },
  { region: "Region D", security: 69, cleaning: 73, landscape: 64, elevator: 78, repair: 72 },
  { region: "Region E", security: 44, cleaning: 51, landscape: 47, elevator: 54, repair: 43 },
  { region: "Region F", security: 95, cleaning: 88, landscape: 83, elevator: 89, repair: 98 },
  { region: "Region G", security: 71, cleaning: 57, landscape: 52, elevator: 62, repair: 68 },
  { region: "Region H", security: 86, cleaning: 79, landscape: 74, elevator: 91, repair: 87 },
];

export const costMapActions = [
  { action: "Normalize security staffing model", impact: "$1.42M", scope: "18 projects", owner: "Cost Ops" },
  { action: "Retender cleaning consumables bundle", impact: "$0.86M", scope: "9 suppliers", owner: "Procurement" },
  { action: "Review elevator maintenance unit price", impact: "$0.64M", scope: "42 lifts", owner: "Asset Desk" },
  { action: "Merge small repair contracts by region", impact: "$0.52M", scope: "31 contracts", owner: "Contract Desk" },
  { action: "Lock fire-system testing package price", impact: "$0.47M", scope: "12 regions", owner: "Asset Desk" },
  { action: "Benchmark waterproof repair unit rates", impact: "$0.39M", scope: "27 projects", owner: "Engineering" },
];

export const contractKpis = [
  { label: "Ledger Contracts", value: "312", delta: "Mock batch 2026-Q2" },
  { label: "Contract Amount", value: "$96.8M", delta: "Fictional ledger" },
  { label: "Pending Payment", value: "$4.18M", delta: "26 items" },
  { label: "Due Soon", value: "38", delta: "Next 45 days" },
  { label: "High Risk", value: "16", delta: "Needs review" },
  { label: "AI Flags", value: "74", delta: "Rule-based mock" },
];

export const contracts = [
  {
    no: "DEMO-CT-2026-001",
    project: "Project Alpha",
    vendor: "Supplier Alpha",
    category: "Security",
    amount: "$860K",
    paid: "64%",
    risk: "High",
    reason: "Payment lag",
  },
  {
    no: "DEMO-CT-2026-014",
    project: "Project Beta",
    vendor: "Supplier Beta",
    category: "Cleaning",
    amount: "$420K",
    paid: "72%",
    risk: "Medium",
    reason: "Due date approaching",
  },
  {
    no: "DEMO-CT-2026-028",
    project: "Project Gamma",
    vendor: "Supplier Gamma",
    category: "Landscape",
    amount: "$215K",
    paid: "51%",
    risk: "High",
    reason: "Missing service period",
  },
  {
    no: "DEMO-CT-2026-033",
    project: "Project Delta",
    vendor: "Supplier Delta",
    category: "Elevator",
    amount: "$310K",
    paid: "81%",
    risk: "Low",
    reason: "On track",
  },
  {
    no: "DEMO-CT-2026-047",
    project: "Project Echo",
    vendor: "Supplier Fox",
    category: "Fire System",
    amount: "$540K",
    paid: "43%",
    risk: "High",
    reason: "Acceptance evidence pending",
  },
  {
    no: "DEMO-CT-2026-052",
    project: "Project Foxtrot",
    vendor: "Supplier Halo",
    category: "Repair",
    amount: "$690K",
    paid: "58%",
    risk: "Medium",
    reason: "Unit price above benchmark",
  },
  {
    no: "DEMO-CT-2026-066",
    project: "Project Harbor",
    vendor: "Supplier Juno",
    category: "Energy",
    amount: "$480K",
    paid: "76%",
    risk: "Low",
    reason: "Within payment plan",
  },
  {
    no: "DEMO-CT-2026-073",
    project: "Project Iota",
    vendor: "Supplier Kite",
    category: "Security Device",
    amount: "$260K",
    paid: "49%",
    risk: "Medium",
    reason: "Warranty clause review",
  },
];

export const qaCases = [
  {
    flow: "Supplier onboarding",
    question: "Can a vendor be approved without complete tax information?",
    answer: "No. The demo rule requires tax identity, contact details, and category scope before approval.",
    evidence: "Matched 3 fictional prior cases",
  },
  {
    flow: "Contract review",
    question: "What should be checked before approving a monthly service payment?",
    answer: "Verify service period, contract coverage, payment lag, and variance against the monthly accrual.",
    evidence: "Matched demo rule group CT-02",
  },
  {
    flow: "Material import",
    question: "Can AI recognition write directly into the price library?",
    answer: "No. Recognition only creates candidates; a reviewer must confirm each item before it enters the library.",
    evidence: "Matched demo rule group ML-01",
  },
  {
    flow: "Cost map",
    question: "Which regions should be reviewed first for repair cost variance?",
    answer: "The demo prioritizes regions with high repair score, high benchmark variance, and open contract actions.",
    evidence: "Matched demo rule group CM-04",
  },
  {
    flow: "Permission center",
    question: "Can an external vendor see cross-region contract exposure?",
    answer: "No. The demo role matrix limits vendors to scoped contract and material views only.",
    evidence: "Matched demo rule group AC-03",
  },
];

export const qaAudit = [
  { type: "Local match", state: "Completed", note: "No external model call" },
  { type: "Vision extract", state: "Mock only", note: "Synthetic document preview" },
  { type: "Deep answer", state: "Optional", note: "Disabled in static demo" },
  { type: "Permission check", state: "Completed", note: "Role-scoped mock answer" },
  { type: "Evidence trace", state: "Completed", note: "Links to fictional rule groups only" },
];

export const roles = [
  {
    role: "System Admin",
    cost: "Full",
    materials: "Full",
    contracts: "Full",
    qa: "Configure",
    account: "Full",
  },
  {
    role: "HQ Cost Reviewer",
    cost: "Full",
    materials: "Approve",
    contracts: "Review",
    qa: "Approve",
    account: "Read",
  },
  {
    role: "Regional Operator",
    cost: "Scoped",
    materials: "Submit",
    contracts: "Scoped",
    qa: "Submit",
    account: "None",
  },
  {
    role: "External Vendor",
    cost: "None",
    materials: "Limited",
    contracts: "Limited",
    qa: "Ask only",
    account: "None",
  },
];

export const safetyRules = [
  "No production repository history",
  "No real database connection",
  "No real uploads or contract files",
  "No secrets, domains, IP addresses or accounts",
  "All records are fictional mock data",
];
